apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-standalone
  labels:
    purpose: mongodb-standalone
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/data/db"