apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    name: gig-api
  name: gig-api
  namespace: applications
spec:
  ports:
    - name: port-9000
      port: 9000
      targetPort: 9000
  selector:
    name: gig-api
  type: ClusterIP
