consumes:
- application/json
host: https://api.gigdemo.opensource.lk:9000/
info:
  contact:
    email: umayangag@opensource.lk
  description: General Information Graph API Documentation
  termsOfService: there are no TOS at this moment, use at your own risk we take no
    responsibility
  title: General Information Graph - API
  version: 1.0.0
paths: {}
produces:
- application/json
schemes:
- https
swagger: "2.0"
